### ISSUE TITLE
Refactoring using NumPy v1.13.0's new block function?

### ISSUE THREAD

**Issue by damontallen** [ritchie46/anaStruct#12]
[NumPy's latest release](https://github.com/numpy/numpy/releases/tag/v1.13.0) has implemented a new function for assembling arrays.  It reminded me of how stiffness matrixes are built and (though I have not reviewed your code) thought you might find it useful in a refactoring pass.

**Comment by ritchie46** [comment]
Wow! The code example of the block function looks really neat. It would sure come in handy for assembling matrices indeed. 

I do plan to add some geometrical non linear options, but I believe I can leave the assembling of the stiffness matrix as is for that..
