### ISSUE TITLE
solve() error

### ISSUE THREAD

**Issue by egyangelo** [ritchie46/anaStruct#120]
<img width="1025" alt="image" src="https://user-images.githubusercontent.com/64504599/213449916-6db5c496-9517-40d5-94c6-caebecd2934a.png">

I have modelled a stair, i'm getting this error while trying to solve()
    
    from anastruct import SystemElements
    from anastruct import LoadCase, LoadCombination
    import numpy as np
    from math import sqrt
    import handcalcs.render
    import forallpeople as si
    si.environment('structural', top_level=True)
    
    %%render
    #short
    t = (200*mm) # Thickness of stair
    w = (1500*mm) # width of Stair
    f_c = (25*MPa) # concrete compressive strength
    gamma_conc = (25 *kN/m**3) # unit weight for concrete
    steps_riser= (170*mm) # step riser
    steps_tread= (300*mm) # step tread
    E = (4700*sqrt(f_c)*1000)*kN/m**2 # Young's Modulus
    
    A = t*w #Area of Stair Section
    I = w*t**3/12 #Interia of Stair Section
    EI_section = E*I
    EA_section = E*A
    DL_factor = 1.40
    LL_factor = 1.60
    
    EI_section = EI_section / mm**4
    EA_section = EA_section / mm**2
    ss = SystemElements(EA=EA_section,EI=EI_section)
    
    # Start Modeling of Stair
    nodes =[(0,0,"f"),(1.5,0,"h"),(4.5,1.8,"f"),(6,1.8,"h"),(9,4,"f"),(11,4,"x")]
    
    for i in range(len(nodes)):
        if i != len(nodes)-1:
            ss.add_element(location=[[nodes[i][0],nodes[i][1]],[nodes[i+1][0],nodes[i+1][1]]])
        match nodes[i][2]:
            case "h":
                ss.add_support_hinged(node_id=i+1)
            case "r":
                ss.add_support_roll(node_id=i+1)
            case "x":
                ss.add_support_fixed(node_id=i+1)
    
    ss.show_structure(scale=0.55)
    # Load Calculation
    %%render
    DL_selfweight = t * gamma_conc
    DL_steps = 0.5 * steps_riser * gamma_conc
    DL_finishing = (1*kPa)
    DL_totalFLight = DL_selfweight + DL_steps + DL_finishing
    DL_totalLanding = DL_selfweight + DL_finishing
    
    DL_totalFLight = DL_totalFLight / kPa
    DL_totalLanding = DL_totalLanding / kPa
    print(DL_totalFLight)
    print(DL_totalLanding)
    
    for element in ss.element_map.items():
        if element[1].angle == 0:
            ss.q_load(q=-DL_totalLanding, element_id=[element[1].id],direction='y')
        else:
            ss.q_load(q=-DL_totalFLight, element_id=[element[1].id],direction='y')
            
    ss.show_structure()
    ss.solve()

**Comment by egyangelo** [comment]
I have locally modified line 195 and it skipped it now
but I still get the same error in the following lines.

**Comment by wolinski** [comment]
Hi @egyangelo 
There is no issue with anastruct. You need to fix conversion EA and EI to unitless values.
EI is kN*mm2 and EI is kN so you need to change this:
`EI_section = EI_section / mm**4
EA_section = EA_section / mm**2`
into:
`EI_section = EI_section/(1*kN*mm**2)
EA_section = EA_section / (1*kN)`

**Comment by egyangelo** [comment]
Thank you for your support :)
