### ISSUE TITLE
Add support roll in inclination?

### ISSUE THREAD

**Issue by TrinhTUHH** [ritchie46/anaStruct#18]
Is it possible to add a roll support not in x or y direction, but, for example in 45° of x-axis?

**Comment by ritchie46** [comment]
Hi, For me this is a low priority, but you are free to make a fork and I can help you.

**Comment by ritchie46** [comment]
Added in commit 4d0966f6317a2fd82eb9c0270b3c75267aec1dcd
Should be tested however.
