### ISSUE TITLE
More section types in database is needed

### ISSUE THREAD

**Issue by lukaszlaba** [ritchie46/anaStruct#21]
It would be nice to have more section defined in database and have section name parameter for method that create element. Also section mark on show_structure figure would be great.  Please find strupy project where already big database of section exist
https://bitbucket.org/struthonteam/strupy/src/master/
There are US, UK and EU sections
https://bitbucket.org/struthonteam/strupy/src/master/strupy/steel/database_sections/
Strupy package can be used as new dependence, or similar solution can be implement in anastruct what is better idea I think. Dose it is good way for anaStruct upgrade?

**Comment by ritchie46** [comment]
I think your solution in your notebooks is good. I could the code snippet below in the documentation so people know how to get going with strupy and Unum. In my opinion its good to have a centralized profile 'database' where we rely on.


```
pip install strupy Unum
```
```
 from strupy.steel.SectionBase import SectionBase
 import strupy.units as u

 sections = SectionBase()
 sections.set_databasename('US')
 sectprop = sections.get_sectionparameters('W14X48')

 E = 200e9
 A = sectprop['Ax'].asUnit(u.m2).asNumber()
 I = sectprop['Iy'].asUnit(u.m4).asNumber()
```

**Comment by lukaszlaba** [comment]
I have just pushed new fork branch with sectionbase included in progress. 
https://github.com/lukaszlaba/anaStruct/tree/sectionbase
It take few days. It will be the same solution like strupy has, but without unum units system needed. Unum is great but anastruct doesn't use any system of units itself - user must care this about and apply consistent units to all quantities.
Finally command like this will be available
`ss.add_element(location=[[0, 0], [0, 5]], sectname='HEA120')`

**Comment by ritchie46** [comment]
Ok, I'll wait and see then. :)

**Comment by lukaszlaba** [comment]
Ritchie find sectionbase fork branch

https://github.com/lukaszlaba/anaStruct/tree/sectionbase

and demo for new features

https://notebooks.azure.com/sRitchie Vink ritchie46inusprojekt/projects/anastruct/html/anastruct_new_features.ipynb

Its look like it work. I hope you enjoy it. Now I need to make more tests. Yours comments are very welcome. The final result of all this job will be pull request approval I hope.

**Comment by ritchie46** [comment]
Hi Lukas,

It looks good! I like what you did with the annotations as well. This is indeed a feature that makes engineering a lot more practical. I will need some time to take a look at the code and will come back on that later. 

For now I do think we should remove the print functions. If anastruct becomes a dependency of another package it should not print to stdout. If we really need to return something to a user, warning and such, we should do that with logging.

**Comment by lukaszlaba** [comment]
Last features I want to add to my sectionbase fork branch is result mark filter and result plot titles.
Here is demo of this features
https://notebooks.azure.com/sinusprojekt/projects/anastruct/html/result_mark_filter_and_plot_titles.ipynb

**Comment by ritchie46** [comment]
I merged your feature into master. Thanks for the effort you've put in. I've made some structural changes, because I want to keep the module to have one clear purpose. So the section base properties are move to that module. Further I've made changes to be pep-8 complient.
