### ISSUE TITLE
Shear Force Diagrams sign conventions reversed.

### ISSUE THREAD

**Issue by johnsonmahama** [ritchie46/anaStruct#229]
The Shear force diagrams have the wrong sign conventions. Negatives are positives while positives are negatives. I think it has to do with the way the forced are added.
Kindly refer to shear force subheading in this link for reference: https://structville.com/2017/08/understanding-sign-conventions-in-structural-analysis.html
Thank you very much.

**Comment by ritchie46** [comment]
These things differ depending on the country you live in.

**Comment by johnsonmahama** [comment]
Oh okay. Thank you very much Ritchie
