### ISSUE TITLE
SystemElements.get_element_results() raises AttributeError

### ISSUE THREAD

**Issue by pp4** [ritchie46/anaStruct#25]
Hi Ritchie,
Congratulations on anaStruct. It's a really great tool.
I have a script that uses the `.get_element_results()` method and it worked last time I used it a few months ago (sorry, but I don't remember which version of anaStruct I had at the time). 
However, now the `.get_element_results()` method returns
> AttributeError: 'Element' object has no attribute 'ai'

This behaviour happens with any model, including the examples in the documentation.
All the best,
Pedro

**Comment by ritchie46** [comment]
Hi Pedro, 
Good to hear that you use it! The bug should be fixed now if you install the master via
`pip install -U git+https://github.com/ritchie46/anaStruct.git`

Did you install from PyPI or from Github last time?

**Comment by pp4** [comment]
Hi Ritchie,
Issue solved!
The latest update works. Many thanks.
I don't remember if I installed anaStructut from PyPI or Github... probably from PyPI.

(offtopic: I have been using anaStruct to make parametric studies and non-linear analyses (reducing element/spring stiffness when some criteria are met); it should soon be ackowledged in a conference paper)

**Comment by ritchie46** [comment]
_(offtopic: I have been using anaStruct to make parametric studies and non-linear analyses (reducing element/spring stiffness when some criteria are met); it should soon be ackowledged in a conference paper)_
Ah.. I knew anaStruct would shine in that! :smile: Really cool, I will look forward to your results!
