### ISSUE TITLE
Using anastruct in Spyder

### ISSUE THREAD

**Issue by doug30** [ritchie46/anaStruct#26]
Hi! I have a university project where I must calculate the forces and strains on a fixed beam using the Python language and would like to represent them in 2D. I created the code below, but it is not running on Spyder. Can you help me?

**a**=float(input("Enter a value for a (mm):"))
**P**=float(input("Enter a value for P (KN)"))
from anastruct import SystemElements
ss = SystemElements()
ss.add_element(location=[700,0])
ss.add_support_fixed(node_id=1)
ss.point_load(ss.id=[**a**], Fy=-1***P**)
ss.show_structure()

**Comment by ritchie46** [comment]
Syder is just a python IDE. Any python package should be able to run in spider.

**Comment by doug30** [comment]
Yes, but what is the path to input the variables "a" and "P" in the ss.point_load () command? It's possible? Sorry, I'm new to programming do not know if my questions is naive.
