### ISSUE TITLE
Element Deflection Discontinuity with High Midspan Point Loads

### ISSUE THREAD

**Issue by smith120bh** [ritchie46/anaStruct#29]
While the following code is an extreme example, it gives an obviously nonsense displacement plot. Note that the maximum displacement (at the midpoint) is correct, but there's an incorrect discontinuity in the plot.
```python
from anastruct import SystemElements
ss = SystemElements(EA=356000, EI=1330)
ss.add_element(location=[[0,0],[10,0]])
ss.add_element(location=[[10,0],[20,0]])
ss.add_support_hinged(node_id=1)
ss.add_support_hinged(node_id=3)
ss.point_load(Fy=-500, node_id=2)
ss.solve()
ss.show_displacement()
```
![image](https://user-images.githubusercontent.com/42363318/68444987-b2373300-022c-11ea-86ab-992adb785e97.png)

I believe the problem is on line 221 of fem/postprocess.py, where 
`w = w - lx * np.sin(alpha)` 
should actually be
`w = w - lx * np.tan(alpha)`

Making this change results in the following displacement graph instead (and the same maximum displacement):
![image](https://user-images.githubusercontent.com/42363318/68446892-2b855480-0232-11ea-93f5-5a79876220c1.png)

**Comment by ritchie46** [comment]
Ah.. I see. Did this change not interfere with plots of more vertical/ diagonal elements?

**Comment by smith120bh** [comment]
It doesn't appear to; see similar code with vertical and diagonal orientations below. I obviously haven't checked every possible use case here, but spot-checking the displacement plots for the example scripts in anaStruct looks good, and the math makes sense to me that `tan()` should be used here instead of `sin()`. That is, `lx` is still based upon the linspace with the length of the *original* element (`element.l`); it's not based upon the hypotenuse between the displaced endpoints.

An alternative fix would be to redefine `lx` as the linspace() between 0 and the length between the displaced endpoints (i.e. `lx = np.linspace(0, (element.l**2 + w[-1]**2)**0.5, con)`), in which case `sin()` would work. I believe either solution would be correct, and either mathematically guarantees that both `element.deflection[0]` and `element.deflection[-1]` ~ 0

Vertical:
![image](https://user-images.githubusercontent.com/42363318/68631544-49f39480-053f-11ea-8e83-1ccb4b15be82.png)

Diagonal:
![image](https://user-images.githubusercontent.com/42363318/68631645-a060d300-053f-11ea-814e-9a62fe38fbc7.png)

**Comment by ritchie46** [comment]
Ah cool.. I will make the modification and take a look at the rest of the examples..
