### ISSUE TITLE
How to cite anaStruct?

### ISSUE THREAD

**Issue by fazaghifari** [ritchie46/anaStruct#32]
Hi,
I'm using anaStruct in my thesis, I would like to cite your project. How do I should cite your project?
Do you have the BibTex format?

Thanks.

**Comment by ritchie46** [comment]
Hi Ghifari,

Cool! I will look forward to your research. Could you give me a heada up?

I think standard github referencing will be sufficient.
https://academia.stackexchange.com/questions/14010/how-do-you-cite-a-github-repository

My full name is Ritchie Vink.

Regards, Ritchie

**Comment by fazaghifari** [comment]
Hi Ritchie,

Thanks for your reply. 

Sure, I'll share my research after I finish my thesis defense and probably some revisions. For a brief intro, I'm conducting research about probabilistic analysis (UQ, Sensitivity Analysis, Reliability analysis) based on Gaussian process regression for a very high dimensional problem. I am using your project as a solver for my test case, truss deflection problem mentioned in [here ](https://www.researchgate.net/publication/304570846_Reliability_analysis_of_high-dimensional_models_using_low-rank_tensor_approximations) .

Regards, Ghifari
