### ISSUE TITLE
Inclined Roller Supports with Q_loads Give Incorrect Results

### ISSUE THREAD

**Issue by smith120bh** [ritchie46/anaStruct#33]
The following two routines should give identical results (after transforming axes), but they do not. With inclined roller supports and q_loads, incorrect reactions are being calculated, and sum of loads does not equal sum of reactions. Point loads appear to work correctly; the problem appears to only be with q_loads.

I tried tracing this back to find the problem. It looks like it's something to do with the `element_primary_force_vector` not being transformed correctly with inclined roller supports, but I wasn't able to pin down exactly where the problem is. 

### Inclined Beam with Y-Axis Roller
```python
from anastruct import SystemElements
ss = SystemElements(EA=356000, EI=1330)
ss.add_element(location=[[0,0],[7.07,7.07]])
ss.add_support_hinged(node_id=1)
ss.add_support_roll(node_id=2, direction="y")
ss.q_load(q=-1, element_id=1, direction="element")
ss.solve()
```
![image](https://user-images.githubusercontent.com/42363318/69844762-b7cee880-12c1-11ea-83aa-302c8ecc3b29.png)
Note that sum of reactions perpendicular to the beam are correctly equal to the total applied load of 10, and an axial load is present.

### Inclined Roller Support
```python
from anastruct import SystemElements
ss = SystemElements(EA=356000, EI=1330)
ss.add_element(location=[[0,0],[10,0]])
ss.add_support_hinged(node_id=1)
ss.add_support_roll(node_id=2, angle=45)
ss.q_load(q=-1, element_id=1, direction="element")
ss.solve()
```
![image](https://user-images.githubusercontent.com/42363318/69844719-8e15c180-12c1-11ea-8061-c2fdec8a5566.png)
Note that sum of reactions perpendicular to the beam are incorrectly equal to 8.54, and no axial load is present.

**Comment by ritchie46** [comment]
Hmm.. Yes, this does't seem to be the case with a single point load indeed. I think it, is from the translation from q-loads to point load in combination with the inclination edge case. Will take a look at it later on.

![image](https://user-images.githubusercontent.com/3023000/69857090-673e9780-128f-11ea-9157-b759a8abc507.png)

**Comment by ritchie46** [comment]
I've ran some tests. The correct results are approached when we discretize to **N** elements where **N** is large. This means the element matrices are correctly assembled. 

``` python
ss = SystemElements(EA=356000, EI=1330)
ss.add_element(location=[[0, 0], [10, 0]])
n = 200
ss.discretize(n)
ss.add_support_hinged(node_id=1)
ss.add_support_roll(node_id=-1, angle=45)
ss.q_load(q=-1, element_id=np.arange(1, n + 1), direction="element")

ss.solve()
ss.show_results()
```

The problem is in the primary force vector. I've derived the formula for different moment stiffnesses in https://github.com/ritchie46/anaStruct/blob/background/primary_m_v.ipynb. This derivation needs to be adapted, so that the angle of the supports is also variable.
