### ISSUE TITLE
Change member properties of an element

### ISSUE THREAD

**Issue by kjjordans** [ritchie46/anaStruct#35]
I was wondering if it was possible to change the member properties (EA, EI) after the model has been defined and solved? I would like to update the members based on displacement.
Currently I am redefining the structure each time.

**Comment by ritchie46** [comment]
This is possible, but can be quite a hassle. This is the basis of the stifness adaptation calculation. https://github.com/ritchie46/anaStruct/blob/1f706c0a956027e42a42436ce212b9ae3c3eba59/anastruct/fem/system_components/solver.py#L8

However, I would recommend writing a function to rebuild a new `SystemElements` object.
