### ISSUE TITLE
Deflection Plots Bi-Directional Integration Error

### ISSUE THREAD

**Issue by smith120bh** [ritchie46/anaStruct#38]
## Problem Description
This displacement plot of a uniformly-loaded propped beam has a sharp corner at the second support that's obviously not correct:
![image](https://user-images.githubusercontent.com/42363318/75002278-f555a300-54b7-11ea-9fd4-996c8be43736.png)

### Code for example above:
```python
from anastruct.fem.system import SystemElements
sys = SystemElements(mesh=250)
sys.add_element(location=[(0.0, 0), (1.3333333333333333, 0)],
                EA=356000.0,
                EI=1332.0000000000002)
sys.add_element(location=[(1.3333333333333333, 0), (2.0, 0)],
                EA=356000.0,
                EI=1332.0000000000002)
sys.add_support_hinged(node_id=sys.find_node_id((0, 0)))
sys.add_support_hinged(node_id=sys.find_node_id((1.3333333333333333, 0)))
sys.q_load(q=-1.0, element_id=1, direction="y")
sys.q_load(q=-1.0, element_id=2, direction="y")
sys.solve()
sys.show_displacement()
```

## Discussion
I saw that a few months ago, the elemental deflections were changed to calculate by means of averaging integrations from both the left and the right. However, there seems to be a flaw in the logic of this, which results in some odd deflection graph shapes and slightly incorrect deflections. The offending code appears to be the following in `postprocess.py/determine_displacements()`:

```python
# Take the average of cumulative integration from both sides. This is due to numerical differences, that
            # would be observable in symmetrical structures.
            phi_neg = (
                -0.5
                * (
                    integrate_array(element.bending_moment, dx)
                    + integrate_array(element.bending_moment[::-1], dx)
                )
                / element.EI
            )
            w = integrate_array(phi_neg, dx)
```

The first `integrate_array()` returns a cumulative sum of the moment from, say, left to right. The second `integrate_array()`, however, flips the moment array such that the moments themselves are right to left, and it never flips them back. In effect, therefore, the deflections from the left side of the beam are partially averaged with the deflection from the right side of the beam. 

Since maximum deflections in a beam are typically near to the beginning, middle, or end of the beam, the maximum deflections are essentially unaffected by this problem - but deflections near the quarter points of asymmetric beams in particular are notably off.

## Proposed solution
I like the idea of integrating in both directions, and that definitely does clean up some asymmetries that shouldn't be there. However, I would suggest running through the full integration in each direction entirely independently, and then flip the reversed array back before averaging both sets of integrations back together:
```python
            dx = element.l / (len(element.bending_moment) - 1)
            lx = np.linspace(0, element.l, con)

            # Take the average of cumulative integration from both sides. This is due to numerical differences, that
            # would be observable in symmetrical structures.
            phi_neg1 = -integrate_array(element.bending_moment,
                                        dx) / element.EI
            w1 = integrate_array(phi_neg1, dx)

            # Angle between last w and elements axis. The w array will be corrected so that this angle == 0.
            alpha1 = np.arctan(w1[-1] / element.l)
            w1 = w1 - lx * np.tan(alpha1)

            phi_neg2 = -integrate_array(element.bending_moment[::-1],
                                        dx) / element.EI
            w2 = integrate_array(phi_neg2, dx)

            # Angle between last w and elements axis. The w array will be corrected so that this angle == 0.
            alpha2 = np.arctan(w2[-1] / element.l)
            w2 = w2[::-1] - lx[::-1] * np.tan(alpha2)

            element.deflection = -(w1 + w2) / 2
            element.max_deflection = np.max(np.abs(element.deflection))
```

### Output of example script with proposed solution
![image](https://user-images.githubusercontent.com/42363318/75002442-92b0d700-54b8-11ea-9293-65dd8f798653.png)
Observe that the slope at that second support is now nearly flat, and there's now a smooth transition at that support.

### Verification
I put together a quick Excel spreadsheet for checking the deflections of a propped beam, based upon the analytical equations for its moments, shears, and deflections. The results are significantly off in the current anaStruct version, but from spot-checking, seem to be accurate to about the third decimal place with the above proposed solution.
[Propped Beam Check Sheet.xlsx](https://github.com/ritchie46/anaStruct/files/4234159/Propped.Beam.Check.Sheet.xlsx)

**Comment by ritchie46** [comment]
Good work! Added this in 1655e25. If this doesn't lead to unexpected behavior, I will do a version bump in a week or two.
