### ISSUE TITLE
Hide diagrams in plots?

### ISSUE THREAD

**Issue by Tarang74** [ritchie46/anaStruct#40]
Can I just have the values appear on the show_axial_force()?

Also can I combine show_structure with show_reaction_force and axial_force?
So that I can see internal forces and external forces without the need of shaded diagrams which obstruct everything.

**Comment by ritchie46** [comment]
No, that isn't possible. You could rewrite the current plotting function to your needs though. But it is probably better to just examine the numeric results. See https://anastruct.readthedocs.io/en/latest/post_processing.html for more info on that.
