### ISSUE TITLE
Designing a Warren Truss 2-d load simulation in Anastruct?

### ISSUE THREAD

**Issue by seyonechithrananda** [ritchie46/anaStruct#42]
Hi @ritchie46! 

Thanks for creating this library! So far it has been really interesting to play around with. I'm looking to use it to test my current bridge design before building it out. However, I'm pretty new to structural analysis + load simulation in Python, and would love any insights you have! The goal would be to visualize points of tension and the load distribution in our bridge, alongside the maximum load (in kilograms the bridge can support.

Here are a couple of diagrams of our design so far! Any help is gladly appreciated!

<img width="654" alt="Screen Shot 2020-05-15 at 5 58 58 PM" src="https://user-images.githubusercontent.com/46096704/82099652-d9882480-96d5-11ea-957a-715d84011663.png">
<img width="556" alt="Screen Shot 2020-05-15 at 5 59 18 PM" src="https://user-images.githubusercontent.com/46096704/82099655-dd1bab80-96d5-11ea-8954-f7de5a977777.png">

**Comment by ritchie46** [comment]
Hi, Looks good. What is the reason of the zero force members in the middle of the bridge? Have you already got an anaStruct model?
