### ISSUE TITLE
el.ai error in intermediate program

### ISSUE THREAD

**Issue by pchandu587** [ritchie46/anaStruct#46]
42 for el in ss.element_map.values():
     43     # apply wind load on elements that are vertical
---> 44     if np.isclose(np.sin(el.ai), 1):
     45         ss.q_load(
     46             q=1,

AttributeError: 'Element' object has no attribute 'ai'

I am getting attribute error issue intermediate program.  How to solve this

**Comment by ritchie46** [comment]
You should take `el.angle` to get the element's angle.
