### ISSUE TITLE
max_force = max(     ValueError: max() arg is an empty sequence in anastruct

### ISSUE THREAD

**Issue by pchandu587** [ritchie46/anaStruct#49]
results = combination.solve(ss)
                for k, ss in results.items():
                      results1[k].show_reaction_force(show=True)

When i used load comination it show error.

File "E:/main/fem_analysis/t_profile.py", line 66, in t_profile_loads
    #results1[k].show_displacement(show=True)
![valueerror](https://user-images.githubusercontent.com/32871570/87629561-e5817880-c750-11ea-9d35-bb51c0dac92c.PNG)

  File "E:\fem_model\fem\system.py", line 910, in show_reaction_force
    return self.plotter.reaction_force(figsize, verbosity, scale, offset, show)
  File "E:\fem_model\fem\plotter\mpl.py", line 669, in reaction_force
    max_force = max(
ValueError: max() arg is an empty sequence

**Comment by ritchie46** [comment]
See #51
