### ISSUE TITLE
How to display results(values or json or object info) with out plot(graphs) when we use Show_results().

### ISSUE THREAD

**Issue by pchandu587** [ritchie46/anaStruct#53]
HI @ritchie46 ,@lukaszlaba, @rodrigo1392  
I want display results(values or json or object info) with out plot(graphs) when we use Show_results().

Thanks for advance.

**Comment by ritchie46** [comment]
You can obtain numerical results. See https://anastruct.readthedocs.io/en/latest/post_processing.html for more info on that. If you want to obtain a summary of all nodes, you have to write your own logic around those provided methods.
