### ISSUE TITLE
Install issues with Matplotlib

### ISSUE THREAD

**Issue by petiesmo** [ritchie46/anaStruct#61]
This issue is not specifically an anaStruct issue, but is impacted due to the matplotlib version == 3.0.3 in requirements.txt

**Comment by Hari-Magara** [comment]
Experiencing the same issue when installing in Windows. Works in my Ubuntu machine though.

**Comment by Hari-Magara** [comment]
@ritchie46 Sorry to bother. Just wondering if you did find some time to have a look at this?

**Comment by ritchie46** [comment]
It isn't really a bug, just a problem with other libs in your environment. If you install the libraries with a different version than anaStruct later (a lower line in you requirements.txt) you probably only get a warning but all should work fine. 

I'll bump the version in the next release though.

**Comment by Hari-Magara** [comment]
Thanks mate. Much appreciated.
