### ISSUE TITLE
Circular / Arch Beam Analyses

### ISSUE THREAD

**Issue by berkdemir** [ritchie46/anaStruct#78]
Hi everyone,

Do you think is it possible to use anaStruct for circular, curved beam analyses? If possible, I will try to use it for tunnel lining analyses.

A simple example I can come up:

```python
import numpy as np
import matplotlib.pyplot as plt
from anastruct import SystemElements


Radius = 5
angle = np.arange(0,360,5)
x = Radius * np.cos(np.radians(angle))
y = Radius * np.sin(np.radians(angle))

ss = SystemElements()
ss.add_element_grid(x,y)

for i in range(1,73,1):
    ss.add_support_spring(i,translation=2,k=10000)
    ss.point_load(i, Fx=100, rotation=45)

ss.solve()
ss.show_structure()
ss.show_axial_force()
ss.show_bending_moment()
```

**Comment by someparsa** [comment]
Hi, I believe that this can be achieved the same as any other node-element analysis approach, which can be used in any finite element and matrix analysis packages. Just use a smaller-sized set of elements with more number of nodes and form the curve of the rounded structure.
