### ISSUE TITLE
BUG detected on tuple strings of a portal

### ISSUE THREAD

**Issue by sunrise125** [ritchie46/anaStruct#79]
Reference is made to such an application:
https://www.ritchievink.com/blog/2017/03/12/python-1d-fem-example-3/
The following commands:
print(ss.get_node_results_system(node_id=2))
print(ss.get_node_results_system(node_id=3))
produce
{'id': 2, 'Fx': 3.019806626980426e-14, 'Fy': 5.329070518200751e-15, 'Ty': 2.842170943040401e-14, 'ux': -0.06264606770288353, 'uy': 0.0037928468734012145, 'phi_y': 0.01282309350473621}
{'id': 3, 'Fx': -2.1316282072803006e-14, 'Fy': -0.0, 'Ty': 7.105427357601002e-15, 'ux': -0.057540201133450423, 'uy': 0.012873819793265443, 'phi_y': 0.002160511813039763}

where bending moment at node-2 Ty should be 23.9, not zero (2.8e-14), same story at node-3, Ty must be 44.2 instead of zero (7.1e-15).

Could someone be so kind to let me know the reason? Thank you

**Comment by smith120bh** [comment]
Hi @sunrise125 , 

This is not actually a bug. The nodal results are using the FEM meaning of 'nodal' results - meaning that they are the reactions at the node, NOT the results for the element that happen to occur at the location of the node. Technically, at node 2, there are two equal and opposite bending moments - a 23.9 moment coming from element 2, and a 23.9 moment coming from element 1. Those balance out, and therefore the moment resultant at node 2 is zero (minus some roundoff error). If you want to find that 23.9 result, you need to pull results from the element, not the node. 

I hope that answers your question!
