### ISSUE TITLE
Make insert_node() not forget supports (was: Point load element)

### ISSUE THREAD

**Issue by mike-mendoza** [ritchie46/anaStruct#92]
How to apply a point load to an element?

**Comment by michaellisitsa** [comment]
I was facing the same question trying to use this. The API docs only allow adding point loads to nodes, not elements. You would need to split your element into two during the initial definition of your structure geometry to make a node at your node location. 

Alternatively, there is an `insert_node` method that allows inserting after-the-fact, per the source code description. This method sets up the `SystemElement` class again, but appears to forget about any assigned supports. So you would need to find the renumbered node_ids and assign supports after.

Clear improvement would be for `insert_node` to retain the assign supports.

```python
# Get id of previously created element
# Keep track of start and end vertices. These will be used later to assign supports.
element_id = ss.add_element(location=(start_vertex, end_vertex))

# Create node at point load location
intermediate_loc = 500 #mm
intermediate_vertex = Vertex(intermediate_loc, 0)

# Insert new node
ss.insert_node(element_id=element_id, location=intermediate_vertex)
intermediate_node = ss.find_node_id(intermediate_vertex)

# Assign point load
ss.point_load(node_id=intermediate_node, Fy=1)

# Assign any supports after all calls to `insert_node` complete
start_node = ss.find_node_id(start_vertex)
end_node = ss.find_node_id(end_vertex) # will be different to nodes created when `add_element` called.

ss.add_support_hinged(node_id=start_node)
ss.add_support_hinged(node_id=end_node)

ss.solve()
```

**Comment by hari-rondo** [comment]
@michaellisitsa - Thanks for the detailed explanation mate. Just wondering if this was fixed. I still get the same issue if I insert and intermediate node to an existing member.

![image](https://github.com/ritchie46/anaStruct/assets/141086101/5e1ec331-cabd-4924-a3b5-561aad70f187)


```
from anastruct import SystemElements
ss = SystemElements(EA=370252200, EI=45860160000)

ss.add_element(location=[[0, 0], [3000, 0]])
ss.insert_node(element_id=1, location=[1500,0])

ss.add_support_hinged(node_id=1)
ss.add_support_roll(node_id=3)

ss.point_load(node_id=2, Fy=-1, rotation=0)

ss.show_structure()

ss.solve(geometrical_non_linear=True) 

ss.show_reaction_force()
ss.show_axial_force()
ss.show_shear_force()
ss.show_bending_moment()
ss.show_displacement()
```
